
/**************************************************************
 *	
 *	dada, 8 bit, 11025Hz,
 *	1 channel, 22324 bytes/channel
 *	Total Size: 1 * 22324 + 4 (header) = 22368 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/PranavBhardwaj_FinalProject/dada.wav
 *	Time-stamp: Wed Nov 25 12:03:42 2015
 *	
 **************************************************************/

#ifndef __DADAH__
#define __DADAH__

#define DADAFREQ 11025
#define DADALEN 22324

extern const unsigned char dada[22324];

#endif /* __DADAH__ */
