
/**************************************************************
 *	
 *	falling, 8 bit, 11025Hz,
 *	1 channel, 56908 bytes/channel
 *	Total Size: 1 * 56908 + 4 (header) = 56952 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/PranavBhardwaj_FinalProject/falling.wav
 *	Time-stamp: Sun Nov 22 12:16:40 2015
 *	
 **************************************************************/

#ifndef __FALLINGH__
#define __FALLINGH__

#define FALLINGFREQ 11025
#define FALLINGLEN 56908

extern const unsigned char falling[56908];

#endif /* __FALLINGH__ */
