
/**************************************************************
 *	
 *	fireballSound, 8 bit, 11025Hz,
 *	1 channel, 20250 bytes/channel
 *	Total Size: 1 * 20250 + 4 (header) = 20294 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/PranavBhardwaj_FinalProject/fireballSound.wav
 *	Time-stamp: Tue Nov 24 18:07:18 2015
 *	
 **************************************************************/

#ifndef __FIREBALLSOUNDH__
#define __FIREBALLSOUNDH__

#define FIREBALLSOUNDFREQ 11025
#define FIREBALLSOUNDLEN 20250

extern const unsigned char fireballSound[20250];

#endif /* __FIREBALLSOUNDH__ */
