
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 289622 bytes/channel
 *	Total Size: 1 * 289622 + 4 (header) = 289666 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/Final_Project/GameSong.wav
 *	Time-stamp: Tue Nov 10 21:01:40 2015
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 289622

extern const unsigned char GameSong[289622];

#endif /* __GAMESONGH__ */
