
/**************************************************************
 *	
 *	openDoor, 8 bit, 11025Hz,
 *	1 channel, 21464 bytes/channel
 *	Total Size: 1 * 21464 + 4 (header) = 21508 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/PranavBhardwaj_FinalProject/openDoor.wav
 *	Time-stamp: Tue Nov 24 21:08:50 2015
 *	
 **************************************************************/

#ifndef __OPENDOORH__
#define __OPENDOORH__

#define OPENDOORFREQ 11025
#define OPENDOORLEN 21464

extern const unsigned char openDoor[21464];

#endif /* __OPENDOORH__ */
