
/**************************************************************
 *	
 *	ping, 8 bit, 11025Hz,
 *	1 channel, 8646 bytes/channel
 *	Total Size: 1 * 8646 + 4 (header) = 8690 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/PranavBhardwaj_FinalProject/ping.wav
 *	Time-stamp: Tue Nov 24 21:04:36 2015
 *	
 **************************************************************/

#ifndef __PINGH__
#define __PINGH__

#define PINGFREQ 11025
#define PINGLEN 8646

extern const unsigned char ping[8646];

#endif /* __PINGH__ */
