
/**************************************************************
 *	
 *	StartSong, 8 bit, 11025Hz,
 *	1 channel, 208211 bytes/channel
 *	Total Size: 1 * 208211 + 4 (header) = 208255 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/FinalProjectStuff/Final_Project/StartSong.wav
 *	Time-stamp: Tue Nov 10 20:20:27 2015
 *	
 **************************************************************/

#ifndef __STARTSONGH__
#define __STARTSONGH__

#define STARTSONGFREQ 11025
#define STARTSONGLEN 208211

extern const unsigned char StartSong[208211];

#endif /* __STARTSONGH__ */
