
/**************************************************************
 *	
 *	StartSFX, 8 bit, 11025Hz,
 *	1 channel, 127296 bytes/channel
 *	Total Size: 1 * 127296 + 4 (header) = 127340 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/LAB12_Sound/StartSFX.wav
 *	Time-stamp: Wed Nov 04 17:06:26 2015
 *	
 **************************************************************/

#ifndef __STARTSFXH__
#define __STARTSFXH__

#define STARTSFXFREQ 11025
#define STARTSFXLEN 127296

extern const unsigned char StartSFX[127296];

#endif /* __STARTSFXH__ */
