
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 447027 bytes/channel
 *	Total Size: 1 * 447027 + 4 (header) = 447071 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Pranav/Desktop/CS2261/LAB12_Sound/TitleSong.wav
 *	Time-stamp: Wed Nov 04 17:06:01 2015
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 447027

extern const unsigned char TitleSong[447027];

#endif /* __TITLESONGH__ */
